### ISSUE TITLE
Misalignment of RTL answers

### ISSUE THREAD

**Issue by atomikaya** [david-swift/Memorize#12]
### Describe the bug

Hi, I'm stress-testing your UI a lil bit by using Memorize to make my English <-> Arabic flashcards. Not a big deal, but the Arabic text (written right-to-left) isn't properly centered. Stylesheet issue probably?

Thanks for the app, it's very straightforward if a bit barebones for now :+1: 

### To Reproduce

A flashcard test you can import:
```
Midday	ظَهيرة
Night	لَيلةٌ
Star	نَجمة
```
The result:
![image](https://github.com/david-swift/Memorize/assets/25960179/1c0bd2fc-457a-4a3c-8d79-1c25bc46e125)

### Expected behavior

Well-centered questions and answers.

**Comment by david-swift** [comment]
Thank you so much for opening the issue (also thanks for the helpful "To Reproduce" section)! I fixed it in 40745e7.
