### ISSUE TITLE
Hide sidebar in initial state

### ISSUE THREAD

**Issue by bragefuglseth** [david-swift/Memorize#14]
### Is your feature request related to a problem? Please describe.- 

The initial state of the app looks awkward, with a completely empty sidebar

### Describe the solution you'd like

When there are no flash card sets, the app should only display a status page with a pill button to create a set (e.g. the current status page, but without the sidebar, and with a button underneath the description instead of the + icon in the corner. See Image Viewer for reference).

### Describe alternatives you've considered

- Open the app directly into set creation on first launch: could work, but a status page serves as a welcoming introduction of the app and provides some breathing space 

### Additional context

Current state:

![Skjermbilde fra 2024-03-08 17-16-12](https://github.com/david-swift/Memorize/assets/91388039/3971b4a7-06ab-4e0e-978f-0753fa75a15b)

Image viewer (proposed source of insipiration):

![Skjermbilde fra 2024-03-08 17-21-52](https://github.com/david-swift/Memorize/assets/91388039/40f5cfcb-0aaa-4bac-80e7-79f245abdcaf)

**Comment by david-swift** [comment]
Hi @bragefuglseth, thank you so much for opening the issue! What do you think about the following onboarding UX?

[Screencast from 2024-03-08 20-10-51.webm](https://github.com/david-swift/Memorize/assets/106754840/76c2d64f-25c6-482a-8298-c05b10908e1a)

**Comment by bragefuglseth** [comment]
Better! The page would be even more welcoming if we turned it from an empty state page into a proper landing page:

- Replace the symbolic with the fullcolor app icon (or an illustration, I can help with that if you're interested)
- Replace "No Sets" with a title-case version of the app slogan ("Study Flashcards")
- Replace the description with "Create a set to start practicing"
- Shorten the button label to "Create Set"

Otherwise this LGTM!

**Comment by david-swift** [comment]
I agree that a landing page would be more welcoming. 

An illustration works better than the app icon as the icon doesn't work on light backgrounds. Thanks for offering your support, I'll definitely need that!

**Comment by david-swift** [comment]
I finally implemented a proper landing page with the app icon:

![Screenshot from 2024-06-08 21-05-52](https://github.com/david-swift/Memorize/assets/106754840/79a6dccb-952e-4447-b481-c1ad6ec7ca66)
