### ISSUE TITLE
'Copy' action needs a toast

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Memorize#18]
### Describe the bug

The 'Copy' action in the 'Export' dialog doesn't give any feedback to the user - whether content was actually copied to the clipboard as intended.

### To Reproduce

1. Edit/create a Set and select 'Export' and click 'Copy'
2. The 'Export' dialog will immediatly close (the content of the Set has been copied to your clipboard but there is no way to know it unless you verify it) 

### Expected behavior

A little toast notification at the end of the second step (when the 'Export' dialog is closed) would be great to inform the user it was correctly copied to the clipboard :)
E.g.: something like "The contents/items of [Set name] have been copied to the clipboard"

**Comment by david-swift** [comment]
Thanks again so much for reporting those details! That's extremely valuable.

**Comment by david-swift** [comment]
I fixed this in 230d3c5.
