### ISSUE TITLE
Polish app icon

### ISSUE THREAD

**Issue by bertob** [david-swift/Memorize#20]
### Describe the bug

App icons with baked-in shadows are a problem in app store UIs because you end up with double shadows when the programmatic shadows are added. See the Flathub guidelines for more detail: https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines

You could probably just mask the shadows in this case so only the part overlaying the bottom card is visible (this is what some other icons do). If you need help with this or any other icon design stuff, feel free to file an issue against [app-icon-requests](https://gitlab.gnome.org/Teams/Design/app-icon-requests), or ask on Matrix in #appicondesign:gnome.org

### To Reproduce

- Open Flathub home/category/app page
- There's a double shadow on the icon

### Expected behavior

No double shadow :)

**Comment by david-swift** [comment]
Thanks! I wanted to check out the App Icon Requests repo as I think the app icon could generally profit from a GNOME designer looking at it. Unfortunately, the link you provided results in a 404 error, and I'm not able to find this repo otherwise. Does the link work for you? Maybe it's a GitLab bug?

**Comment by bertob** [comment]
It definitely exists, but I think it's only visible if you're logged in :)

**Comment by david-swift** [comment]
I'm logged in and can access other repos of the Design team (e.g. app-illustrations, app-mockups, ...), but app-icon-requests is not in the list of their repos and the link leads to a 404 error for some reason.
