### ISSUE TITLE
Jumping straight into editing mode when creating a new set

### ISSUE THREAD

**Issue by bragefuglseth** [david-swift/Memorize#25]
When you create a new set, it's likely that you'll want to give it a name and fill it with something right away. Because of this, it would make sense to jump right into its editing mode once it gets created.

**Comment by david-swift** [comment]
https://github.com/david-swift/Memorize/assets/106754840/72f26b17-5df0-40a7-a262-72f889a8e4b6

Implemented in 214e534.

**Comment by bragefuglseth** [comment]
Awesome!! The cherry on top would be to use "New Set" as the window title there instead of "Edit Set" :smiley_cat:

**Comment by david-swift** [comment]
Implemented this in d145898
