### ISSUE TITLE
Using an adaptive dialog for set editing

### ISSUE THREAD

**Issue by bragefuglseth** [david-swift/Memorize#26]
Libadwaita 1.5 comes with new [adaptive dialogs](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.5/class.Dialog.html), that adapt to the parent window size and turn into bottom sheets on narrow window widths. It would be neat if the set editing view could utilize such a dialog.

**Comment by david-swift** [comment]
https://github.com/david-swift/Memorize/assets/106754840/95b5568c-ce2d-4792-8155-666e9336dd82

Implemented in 2229b60.
