### ISSUE TITLE
Reorganizing header bar buttons in "main" flash card view

### ISSUE THREAD

**Issue by bragefuglseth** [david-swift/Memorize#27]
One last design suggestion: With the design suggested in #24, there would be some leftover space in the header bar of the main "flash card" view of sets. Since deleting and exporting a set aren't really actions that *edit* the set, I think it would make sense to move them out into the header bar there instead. The edit button could also be moved there, to make it clear that it edits the whole set, not just the name:

![Skjermbilde fra 2024-03-18 22-38-02](https://github.com/david-swift/Memorize/assets/91388039/8f0084e7-bc1a-4890-9a89-9b8c96d4c744)

In addition to being semantically better, this would make it a lot quicker to delete unwanted sets.

If more actions that apply to the entire set are added in the future, we could group them together with deleting and exporting in a three-dot popover menu instead.

**Comment by david-swift** [comment]
Thanks! I really like that concept, I'll look into implementing it once I'm less busy.

**Comment by david-swift** [comment]
![Screenshot from 2024-03-21 21-46-30](https://github.com/david-swift/Memorize/assets/106754840/d4c7b6bc-17c5-4c3d-9d8b-ec2f6e147db7)

I implemented it in 2229b60.

**Comment by bragefuglseth** [comment]
How exciting! :grinning:
