### ISSUE TITLE
'Export' action causes crash when Set is empty

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Memorize#30]
### Describe the bug

Clicking the 'Export Set' button makes the app crash if there is no Flashcard in the Set.
 

### To Reproduce

1. Create an empty set and remove the 2 default question templates
2. Click 'Export set'

### Expected behavior

I didn't expect that button to produce anything when the set is empty anyway ^^. Nonetheless it should at least be 'greyed out'/defined as not clickable to avoid this

**Comment by david-swift** [comment]
Fixed in e8a0387 (on the branch 46). Thanks!
