### ISSUE TITLE
Move from OverlaySplitView to NavigationSplitView

### ISSUE THREAD

**Issue by bragefuglseth** [david-swift/Memorize#33]
I'm really enjoying the latest changes, great work! Semantically, I think it would make more sense to use a hierarchical navigation model for the main view at narrow window widths than an overlay sidebar based one, since the app has a clear top-down structure (list of sets -> set info -> study/test modes). AdwNavigationSplitView implements this hierarchical model.

**Comment by david-swift** [comment]
I implemented this in 8ff3c7b. Thanks!
