### ISSUE TITLE
Cannot edit flashcard contents

### ISSUE THREAD

**Issue by comshc** [david-swift/Memorize#42]
### Describe the bug

When editing the back of the flashcard, the front is cleared and the back is distorted.

[Screen recording with screenkeys on.](https://github.com/david-swift/Memorize/assets/156095144/a2daa6aa-4c49-4303-93a1-c58a294b5465)

### To Reproduce

1. Create new set
2. Click on 'Edit set'
3. Create a new card (or edit an existing one).
4. Modify the "back" of the card
5. Witness the front side clear, and the back mutilated

### Expected behavior

Editing one field does not change other fields, and it shows exactly what I type in the order I typed it.

### Additional context

Version 0.2.1 on Arch.

**Comment by david-swift** [comment]
How could I not see this before the release? Thanks so much for reporting, fixed in c66a52d. I'll immediately release the next version with the fix!
