### ISSUE TITLE
Ability to apply tags to multiple flashcards at once

### ISSUE THREAD

**Issue by Heus-Sueh** [david-swift/Memorize#47]
### Is your feature request related to a problem? Please describe.

Yes, I want to apply a tag to several flashcards but the current workflow doesn't help much

### Describe the solution you'd like

a more practical and easy way to select multiple flashcards and apply a tag or several tags

### Describe alternatives you've considered

 none

### Additional context

the way it currently works, you waste a lot of time using the mouse scroll and selecting which tag you want to apply to the chosen flashcard

**Comment by david-swift** [comment]
Sorry for ignoring your feature requests and bug report for such a long time. I was quite busy and still am rather busy so please don't expect them to be implemented very soon. Thank you for opening those issues, this is really helpful!

**Comment by Heus-Sueh** [comment]
> Sorry for ignoring your feature requests and bug report for such a long time. I was quite busy and still am rather busy so please don't expect them to be implemented very soon. Thank you for opening those issues, this is really helpful!

No problem, do things in your own time and if you want, don't feel pressured to work on things you're not motivated to do :+1:

**Comment by david-swift** [comment]
I added the new view in commit 2cb7513:

![Screenshot from 2024-06-08 18-45-18](https://github.com/david-swift/Memorize/assets/106754840/6f4256d7-d8b6-4876-b718-73387adb0fb0)

Thanks @Heus-Sueh for opening the issue!
