### ISSUE TITLE
Typing 'Del' on keyboard asks to delete the set

### ISSUE THREAD

**Issue by rene-coty** [david-swift/Memorize#49]
### Describe the bug

If 'Del' is pressed when typing in the text field of a flashcard, the text field will immediatly lose focus and the app will ask if you wish to delete the entire set, which isn't expected and can lead to unwanted suppression of the set

### To Reproduce

1. Open a set
2. Edit a flashcard
3. Press 'Del' while editing

### Expected behavior

The 'Del' key should only affect the text in the input field, ie. erase the caracter behind

**Comment by david-swift** [comment]
Thank you so much for opening the issues. I'll work on them once I'm less busy (which won't be the case in the next days).
